/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { PostStorage__factory } from "./PostStorage__factory";
export { TipPost__factory } from "./TipPost__factory";
